// Mirrors backend PermissionSeeder.java's role -> permission grants by hand.
// Keep in sync the same way constants/enums.js already is.

const HR_ADMIN_PERMISSIONS = [
  'COMPANY_READ',
  'DEPARTMENT_MANAGE', 'DEPARTMENT_READ',
  'DESIGNATION_MANAGE', 'DESIGNATION_READ',
  'EMPLOYEE_CREATE', 'EMPLOYEE_READ', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE',
  'SHIFT_MANAGE', 'SHIFT_READ',
  'SHIFT_SCHEDULE_MANAGE', 'SHIFT_SCHEDULE_READ',
  'ATTENDANCE_READ', 'ATTENDANCE_GENERATE', 'ATTENDANCE_CORRECT', 'ATTENDANCE_UNLOCK',
  'HOLIDAY_MANAGE', 'HOLIDAY_READ',
  'LEAVE_APPLY', 'LEAVE_READ', 'LEAVE_SUPERVISOR_APPROVE', 'LEAVE_APPROVE',
  'LEAVE_BALANCE_READ', 'LEAVE_BALANCE_MANAGE',
  'SALARY_RULE_READ', 'SALARY_RULE_MANAGE',
  'PAYROLL_PROCESS', 'PAYROLL_READ',
  'SALARY_SLIP_READ',
  'REPORT_READ',
  'DASHBOARD_READ',
];

export const ROLE_PERMISSIONS = {
  HR: HR_ADMIN_PERMISSIONS,
  ADMIN: [...HR_ADMIN_PERMISSIONS, 'AUDIT_READ', 'ROLE_MANAGE', 'ROLE_READ'],
  SUPERVISOR: [
    'COMPANY_READ',
    'DEPARTMENT_READ',
    'DESIGNATION_READ',
    'EMPLOYEE_READ',
    'SHIFT_READ',
    'SHIFT_SCHEDULE_MANAGE', 'SHIFT_SCHEDULE_READ',
    'ATTENDANCE_READ',
    'HOLIDAY_READ',
    'LEAVE_APPLY', 'LEAVE_READ',
    'LEAVE_SUPERVISOR_APPROVE',
    'LEAVE_BALANCE_READ',
    'PAYROLL_READ',
    'SALARY_SLIP_READ',
    'REPORT_READ',
    'DASHBOARD_READ',
  ],
  EMPLOYEE: [
    'COMPANY_READ',
    'DEPARTMENT_READ',
    'DESIGNATION_READ',
    'EMPLOYEE_READ',
    'SHIFT_READ',
    'SHIFT_SCHEDULE_READ',
    'ATTENDANCE_READ',
    'HOLIDAY_READ',
    'LEAVE_APPLY', 'LEAVE_READ',
    'LEAVE_BALANCE_READ',
    'SALARY_SLIP_READ',
  ],
  PLATFORM_OWNER: ['COMPANY_CREATE', 'COMPANY_READ', 'COMPANY_UPDATE', 'COMPANY_DELETE', 'AUDIT_READ', 'AUDIT_MANAGE'],
  PLATFORM_ADMIN: ['COMPANY_CREATE', 'COMPANY_READ', 'COMPANY_UPDATE', 'COMPANY_DELETE', 'AUDIT_READ', 'AUDIT_MANAGE'],
};

// Every grantable code, in the same order as the backend's PermissionCode enum -
// used to render the custom-role permission checklist. Platform-only codes are
// listed separately so the UI can omit them (CustomRoleService.setPermissions
// rejects them outright).
export const PERMISSION_CODES = [
  'DEPARTMENT_MANAGE', 'DEPARTMENT_READ',
  'DESIGNATION_MANAGE', 'DESIGNATION_READ',
  'EMPLOYEE_CREATE', 'EMPLOYEE_READ', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE',
  'SHIFT_MANAGE', 'SHIFT_READ',
  'SHIFT_SCHEDULE_MANAGE', 'SHIFT_SCHEDULE_READ',
  'ATTENDANCE_READ', 'ATTENDANCE_GENERATE', 'ATTENDANCE_CORRECT', 'ATTENDANCE_UNLOCK',
  'HOLIDAY_MANAGE', 'HOLIDAY_READ',
  'LEAVE_APPLY', 'LEAVE_READ', 'LEAVE_SUPERVISOR_APPROVE', 'LEAVE_APPROVE',
  'LEAVE_BALANCE_READ', 'LEAVE_BALANCE_MANAGE',
  'SALARY_RULE_READ', 'SALARY_RULE_MANAGE',
  'PAYROLL_PROCESS', 'PAYROLL_READ',
  'SALARY_SLIP_READ',
  'REPORT_READ',
  'DASHBOARD_READ',
  'ROLE_MANAGE', 'ROLE_READ',
  'COMPANY_READ', 'AUDIT_READ',
];

// COMPANY_CREATE/UPDATE/DELETE and AUDIT_MANAGE are the only codes
// CustomRoleService.setPermissions rejects outright (see SECURITY.md Phase 10) -
// never offered in a custom role's permission checklist, mirroring that guard.
export const PLATFORM_ONLY_CODES = ['COMPANY_CREATE', 'COMPANY_UPDATE', 'COMPANY_DELETE', 'AUDIT_MANAGE'];

export const hasPermission = (role, code) => !!role && (ROLE_PERMISSIONS[role] || []).includes(code);
