import { useEffect, useState } from 'react';
import dayjs from 'dayjs';
import TextField from '@mui/material/TextField';
import Alert from '@mui/material/Alert';
import PageHeader from '../../components/PageHeader';
import DataTable from '../../components/DataTable';
import StatusChip from '../../components/StatusChip';
import MoneyText from '../../components/MoneyText';
import EmployeePicker from '../../components/EmployeePicker';
import payrollApi from '../../api/payroll';
import { PAYROLL_STATUS_COLOR } from '../../constants/enums';

const columns = [
  { field: 'revision', headerName: 'Revision', width: 90 },
  {
    field: 'status',
    headerName: 'Status',
    width: 130,
    renderCell: (params) => <StatusChip value={params.value} colorMap={PAYROLL_STATUS_COLOR} />,
  },
  {
    field: 'generatedAt',
    headerName: 'Generated at',
    width: 180,
    valueFormatter: (v) => (v ? dayjs(v).format('DD MMM YYYY HH:mm') : ''),
  },
  { field: 'generatedBy', headerName: 'Generated by', width: 130 },
  { field: 'payableDays', headerName: 'Payable days', width: 110 },
  {
    field: 'totalEarnings',
    headerName: 'Earnings',
    width: 130,
    renderCell: (params) => <MoneyText value={params.value} />,
  },
  {
    field: 'totalDeduction',
    headerName: 'Deductions',
    width: 130,
    renderCell: (params) => <MoneyText value={params.value} />,
  },
  {
    field: 'netSalary',
    headerName: 'Net salary',
    width: 140,
    renderCell: (params) => <MoneyText value={params.value} />,
  },
];

export default function EmployeeHistory() {
  const [employeeId, setEmployeeId] = useState(null);
  const [month, setMonth] = useState('');
  const [year, setYear] = useState('');
  const [rows, setRows] = useState([]);
  const [allRows, setAllRows] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!employeeId) {
      setAllRows([]);
      return;
    }
    setLoading(true);
    payrollApi
      .forEmployee(employeeId)
      .then(setAllRows)
      .catch(() => setAllRows([]))
      .finally(() => setLoading(false));
  }, [employeeId]);

  useEffect(() => {
    if (!employeeId || !month || !year) {
      setRows(allRows);
      return;
    }
    setLoading(true);
    payrollApi
      .revisions(employeeId, Number(month), Number(year))
      .then(setRows)
      .catch(() => setRows([]))
      .finally(() => setLoading(false));
  }, [employeeId, month, year, allRows]);

  return (
    <>
      <PageHeader
        title="Employee Payroll History"
        subtitle="Every generation is a snapshot — raising a salary today never changes an old payslip"
        actions={
          <>
            <EmployeePicker label="Employee" value={employeeId} onChange={setEmployeeId} />
            <TextField
              size="small"
              label="Month (optional)"
              value={month}
              onChange={(e) => setMonth(e.target.value.replace(/[^0-9]/g, ''))}
              sx={{ width: 150 }}
            />
            <TextField
              size="small"
              label="Year (optional)"
              value={year}
              onChange={(e) => setYear(e.target.value.replace(/[^0-9]/g, ''))}
              sx={{ width: 130 }}
            />
          </>
        }
      />
      {!employeeId ? (
        <Alert severity="info">Pick an employee to see their payroll history.</Alert>
      ) : (
        <DataTable rows={rows} columns={columns} loading={loading} getRowId={(r) => r.id} height={560} />
      )}
    </>
  );
}
